### ISSUE TITLE
Error - Launch configuration ContactConfirm.feature references non-existing project pytest-bdd-example-master.

### ISSUE THREAD

**Issue by pradeepbhat1** [VirtaKuivapuu/pytest-bdd-example#1]
Hi,
I downloaded the python project and imported into Eclipse. i have installed Pydev and Cucumber(to see the feature file contents in gherkin format). when i right click in any of the feature files and run as "cucumber file", i get the below error mesage - 
"Launch configuration ContactConfirm.feature references non-existing project pytest-bdd-example-master."

Also it shows the step doesn't have matching glue code. I have tried all steps but nothing is working.

Any help here will be really appreciated.

![image](https://user-images.githubusercontent.com/27555918/28248189-d1ba5cd4-6a5d-11e7-963e-e99c192d3458.png)

**Comment by CredoQuiaAbsurdum** [comment]
Hi,

I did not use any IDE for this example, and I am not familiar with Pydev. So I am not sure why this happened.
Did you install pytest and pytest-bdd?
Try to use command lines see how it works.

**Comment by pradeepbhat1** [comment]
Hi,
Thanks for your reply. Really appreciate your response.

I'm trying to use eclipse by installing pydev plugin and cucumber plugin.

I was trying with behave technique. I've not tried pytest. Since I'm not
familiar with command line. Will try it. Thanks again

Regards
Pradeep Bhat

On Jul 19, 2017 9:46 PM, "Yuxuan Zhao" <notifications@github.com> wrote:

Hi,

I did not use any IDE for this example and I am not familiar with Pydev. So
I am not sure why this happened.
Did you install pytest and pytest-bdd?
Try to use command lines see how it works.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/VirtaKuivapuu/pytest-bdd-example/issues/1#issuecomment-316437870>,
or mute the thread
